public class BoardModel {

    private BoardHouse[][] board = { { new BoardHouse(BoardPieces.ROOK, BoardPlayers.BLACK),
            new BoardHouse(BoardPieces.KNIGTH, BoardPlayers.BLACK),
            new BoardHouse(BoardPieces.BISHOP, BoardPlayers.BLACK),
            new BoardHouse(BoardPieces.KING, BoardPlayers.BLACK), new BoardHouse(BoardPieces.QUEEN, BoardPlayers.BLACK),
            new BoardHouse(BoardPieces.BISHOP, BoardPlayers.BLACK),
            new BoardHouse(BoardPieces.KNIGTH, BoardPlayers.BLACK),
            new BoardHouse(BoardPieces.ROOK, BoardPlayers.BLACK) },
            { new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE), new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE) },
            { new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE), new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE) },
            { new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE), new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE) },
            { new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE), new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE) },
            { new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE), new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.NONE, BoardPlayers.NONE) },
            { new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE), new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE),
                    new BoardHouse(BoardPieces.PAWN, BoardPlayers.NONE) },
            { new BoardHouse(BoardPieces.ROOK, BoardPlayers.WHITE),
                    new BoardHouse(BoardPieces.KNIGTH, BoardPlayers.WHITE),
                    new BoardHouse(BoardPieces.BISHOP, BoardPlayers.WHITE),
                    new BoardHouse(BoardPieces.KING, BoardPlayers.WHITE),
                    new BoardHouse(BoardPieces.QUEEN, BoardPlayers.WHITE),
                    new BoardHouse(BoardPieces.BISHOP, BoardPlayers.WHITE),
                    new BoardHouse(BoardPieces.KNIGTH, BoardPlayers.WHITE),
                    new BoardHouse(BoardPieces.ROOK, BoardPlayers.WHITE) } };
}
